### //login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "tester01",
  "password": "GteteqbQQgSr88SwNExUQv2ydb7xuf8c"
}

###

### 1. Hämta alla fakturor
GET http://localhost:3000/api/bills
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"c8906b535286c2c76264e26b9b559442"}

###

### 2. Hämta faktura med ID
GET http://localhost:3000/api/bill/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"c8906b535286c2c76264e26b9b559442"}

###

### 3. Radera faktura med ID
DELETE http://localhost:3000/api/bill/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"ee399bb21589894c2dad35f8d113989d"}

###

### 4. Hitta alla kunder
GET http://localhost:3000/api/clients
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"c959cbec6f69ecfcc23d07c1f9c898e7"}

###

### 5. Uppdatera bokning
PUT http://localhost:3000/api/reservation/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"3eeab084399d7daafd179f22211c326b"}

{
  "start": "2024-12-26",
  "end": "2025-01-02",
  "client": "Alexandra Andersson",
  "room": "Floor 3, Room 302",
  "bill": "ID: 1"
}

###

### 6. Skapa ny kund
POST http://localhost:3000/api/client/new
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"c959cbec6f69ecfcc23d07c1f9c898e7"}

{
  "name": "Jonas Jonasson",
  "email": "Jonas.Jonasson@example.com",
  "telephone": "0701234567"
}

###

### 7. Hitta kund med ID
GET http://localhost:3000/api/client/2
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"c959cbec6f69ecfcc23d07c1f9c898e7"}

###

### 8. Uppdatera kund
PUT http://localhost:3000/api/client/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"c959cbec6f69ecfcc23d07c1f9c898e7"}